<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SYS0081" name="Login-test" tests="3" failures="2" timestamp="13 Nov 2014 09:07:51 GMT" time="94.707" errors="0">
  <testcase name="checkUserLogin" time="11.89" classname="com.diw.test.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.diw.test.LoginTest.checkUserLogin(LoginTest.java:40)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkUserLogin -->
  <testcase name="checkUserLogout" time="2.3" classname="com.diw.test.LoginTest"/>
  <testcase name="checkRegistration" time="61.308" classname="com.diw.test.RegistrationTest">
    <failure type="java.lang.AssertionError" message="Time out exception is occurred">
      <![CDATA[java.lang.AssertionError: Time out exception is occurred
	at com.diw.action.UserActions.getWebElement(UserActions.java:57)
	at com.diw.action.UserActions.getText(UserActions.java:121)
	at com.diw.test.RegistrationTest.checkRegistration(RegistrationTest.java:35)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- checkRegistration -->
</testsuite> <!-- Login-test -->
